#!/usr/bin/env python

import logging

from argparse import ArgumentParser

import pydentity.server

PARSER = ArgumentParser(description="Web IAM for Samba4")
PARSER.add_argument("--host",
                    help="Interface to listen on")
PARSER.add_argument("--port", "-p", type=int,
                    help="Port to listen on")

PARSER.add_argument("--smbdomain", required=True, metavar="DOMAIN",
                    help="Samba domain to use")
PARSER.add_argument("--smbconf", default="/etc/samba/smb.conf", metavar="FILE",
                    help="Samba config file to load details from")

PARSER.add_argument("--debug", default=False, action='store_true',
                    help="Turn debug mode on")

def main():
    args = PARSER.parse_args()
    logging.basicConfig(format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
                        level=logging.INFO,
                        )
    pydentity.server.run(args)

if __name__ == '__main__':
    main()
